# Generated by Django 5.1.3 on 2024-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_records',
            name='url',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='email',
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
