# Generated by Django 5.1.3 on 2024-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_access_records_url_remove_webpage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='ntg@gmail.com', max_length=254),
        ),
    ]
